---
title: "BDA - Project brms library test"
author: "Arsi Ikäheimonen"
output:
  pdf_document:
    toc: yes
    toc_depth: 1
  html_document:
    toc: yes
    toc_depth: '1'
    df_print: paged
urlcolor: blue
---

\newpage

Load packages
```{r message=FALSE, warning=FALSE}
library(aaltobda)
library(cmdstanr)
library(brms)
library(ggplot2)
library(gridExtra)
library(bayesplot)
library(ggdist)
theme_set(bayesplot::theme_default(base_family = "sans"))
library(rprojroot)
library(brms)
library(caret)
library(corrplot)
library(dplyr)
library(crosstable)
library(patchwork)
SEED <- 614273
```


Load data
```{r}
data <- read.csv('https://raw.githubusercontent.com/aaron-r-campbell/AALTO-CS-E5710-Bayesian-Data-Analysis-D-Project/main/Machine-Learning-with-R-datasets/insurance.csv')
head(data)
```

Typecasting
```{r}
data$region <- as.factor(data$region)
data$sex <- as.factor(data$sex)
data$smoker <- as.factor(data$smoker)
data$children <- as.integer(data$children)
data$region = recode(data$region, "southeast" = "south", "southwest" = "south", "northeast" = "north", "northwest" = "north")
head(data)
```
Scaler functions
```{r}
min_max_scaler <- function(values){
  scaled_data = (values - min(values)) / (max(values) - min(values))
  return(scaled_data)
}

descaler <- function(values, max, min){
  descaled_data = values*(max-min) + min
  return(descaled_data)
}
```
Scale the data
```{r}
data$scaled_charges = min_max_scaler(data$charges)
data$scaled_age = min_max_scaler(data$age)
data$scaled_bmi = min_max_scaler(data$bmi)
data$scaled_children = min_max_scaler(data$children)
head(data)
```
Train / test data
```{r}
inTrain <- createDataPartition(
  y = data$charges,
  ## the outcome data are needed
  p = .75,
  ## The percentage of data in the
  ## training set
  list = FALSE
)

train_data <- data[inTrain,]
test_data <- data[-inTrain,]
cat(paste0('train_data: ',dim(train_data)[1],' observations\ntest_data:  ',dim(test_data)[1],' observations\n'))
```

Distributions of the variables:
```{r}
age_fig <- ggplot(data, aes(x=age)) + 
    geom_histogram(fill="#d3d3d3",color="#000000",breaks=seq(min(data$age),max(data$age),length.out=11), bins=10) +
    labs(x="Age (years)", y="Frequency") + 
    scale_x_continuous(breaks=as.integer(seq(min(data$age), max(data$age), length.out=6)))
   
sex_fig <- ggplot(data, aes(x=sex)) + 
    geom_bar(fill="#d3d3d3",color="#000000",width=0.5) +
    labs(x="Sex", y="Frequency") +
    geom_text(stat='count', aes(label=after_stat(count)), vjust=-0.5) + 
    coord_cartesian(ylim=c(0,700))
   
bmi_fig <- ggplot(data, aes(x=bmi)) + 
    geom_histogram(fill="#d3d3d3",color="#000000", bins=30) +
    labs(x=expression(paste('BMI ', bgroup("(", frac(kg,m^2), ")"))), y="Frequency") +
    scale_x_continuous(breaks=as.integer(seq(min(data$bmi), max(data$bmi), length.out=5)))
   
children_fig <- ggplot(data, aes(x=children)) + 
    geom_bar(fill="#d3d3d3",color="#000000") +
    labs(x="Number of children", y="Frequency") +
    geom_text(stat='count', aes(label=after_stat(count)), vjust=-0.5) + 
    scale_x_continuous(breaks=min(data$children):max(data$children), labels=sapply(min(data$children):max(data$children), function(x) toString(x))) +
    coord_cartesian(ylim=c(0,600))
   
smoker_fig <- ggplot(data, aes(x=smoker)) +
    geom_bar(fill="#d3d3d3",color="#000000",width=0.5) +
    labs(x="Smoker", y="Frequency") +
    geom_text(stat='count', aes(label=after_stat(count)), vjust=-0.5) +
    coord_cartesian(ylim=c(0,1150))
   
region_fig <- ggplot(data, aes(x=region)) + 
    geom_bar(fill="#d3d3d3",color="#000000",width=0.5) +
    labs(x="Region (USA)", y="Frequency") +
    geom_text(stat='count', aes(label=after_stat(count)), vjust=-0.5) +
    coord_cartesian(ylim=c(0,730))
   
charges_fig <- ggplot(data, aes(x=charges)) + 
    geom_histogram(fill="#d3d3d3",color="#000000", bins=30) +
    labs(x="Price ($)", y="Frequency")
```

Plotting in single figure
```{r Fig1, echo=TRUE, fig.height=12, fig.width=8}
fig <- (age_fig+sex_fig)/(bmi_fig+region_fig)/(children_fig+smoker_fig)/charges_fig +
    plot_annotation(
        title = 'Distribution of the explanitory variables.',
        tag_levels = 'A') +
    plot_layout(heights = c(1,1,1,1.5))
fig
ggsave("dist_all.pdf", plot = fig, width = 8, height = 12)
```
Basic frequentist linear model
```{r}
basic_model = lm(charges~age+sex+bmi+children+smoker+region, data = data) #Create the linear regression
summary(basic_model) #Review the results
```
Check the data balance
```{r}
crosstable(data, c(smoker,), by=region)
```

PRIORS:

```{r}
# Prior choice (used for all the models except the hierarchical model)
pr = prior(normal(0,1), class = 'b') 

pr2 = (prior(normal(0,1), class = "b", coef = "scaled_age") +
            prior(student_t(3,0,0.1), class="sd", group="smoker"))

pr3 = (prior(normal(0,1), class = "b", coef = "scaled_age") +
       prior(normal(0,1), class="b", coef ="scaled_bmi") +
       prior(student_t(3,0,0.1), class="sd", group="smoker"))

pr4 = (prior(normal(0,1), class = "b", coef = "scaled_age") +
       prior(normal(0,1), class="b", coef ="scaled_bmi") +
       prior(student_t(3,0,0.1), class="sd", group="smoker") + 
       prior(student_t(3,0,0.1), class="sd", group="region"))

pr5 = (prior(normal(0,1), class = "b", coef = "scaled_age") +
      prior(normal(0,1), class = "b", coef = "sexmale") +
      prior(normal(0,1), class="b", coef ="scaled_bmi") +
      prior(normal(0,1), class="b", coef ="scaled_children") +
      prior(student_t(3,0,0.1), class="sd", group="region") +
      prior(student_t(3,0,0.1), class="sd", group="smoker"))

```

MODELS:
```{r message=FALSE, warning=FALSE, results='hide'}
# Baseline model
model_baseline = brm(
  scaled_charges ~ scaled_age,
  data  = train_data,
  prior = pr,
  cores = 4
)

# 2 effect model with BMI
model_2_test1 = brm(
  scaled_charges ~ scaled_age + scaled_bmi, 
  data  = train_data,
  prior = pr,
  cores = 4
)

# 2 effect non-hierarchical model with smoker
model_2_test2 = brm(
  scaled_charges ~ scaled_age + smoker, 
  data  = train_data,
  prior = pr,
  cores = 4
)

# 2 effect hierarchical model with smoker
model_2 = brm(
  scaled_charges ~ scaled_age + (1|smoker), 
  data  = train_data,
  prior = pr2,
  cores = 4
)
```


```{r message=FALSE, warning=FALSE, results='hide'}
# 3 effect hierarchical model
model_3 = brm(
  scaled_charges ~ scaled_age + scaled_bmi + (1|smoker), 
  data  = train_data,
  prior = pr3,
  cores = 4
)

# 4 effect hierarchical model
model_4 = brm(
  scaled_charges ~ scaled_age + scaled_bmi + (1|smoker) + (1|region), 
  data  = train_data,
  prior = pr4,
  cores = 4
)

# 5 effect non-hierarchical model
model_5_non_hier = brm(
  scaled_charges ~ scaled_age + sex + scaled_bmi + scaled_children + region + smoker, 
  data  = train_data,
  prior = pr,
  cores = 4
)

# 5 effect hierarchical model
model_5 = brm(
  scaled_charges ~ scaled_age + sex + scaled_bmi + scaled_children + (1|region) + (1|smoker),
  data  = train_data,
  prior = pr5,
  cores = 4,
  control = list(adapt_delta = 0.9)
)
```

```{r}
summary(model_baseline)
loo_baseline = loo(model_baseline)
loo_baseline
```

```{r}
summary(model_2_test1)
loo_2_test1 = loo(model_2_test1)
loo_2_test1
```
```{r}
summary(model_2_test2)
loo_2_test2 = loo(model_2_test2)
loo_2_test2
```


```{r}
summary(model_2)
loo_2 = loo(model_2)
loo_2
```


```{r}
summary(model_3)
loo_3 = loo(model_3)
loo_3
```



```{r}
summary(model_4)
loo_4 = loo(model_4)
loo_4
```





```{r}
summary(model_5_non_hier)
loo_5_non_hier = loo(model_5_non_hier)
loo_5_non_hier
```



```{r}
summary(model_5)
loo_5 = loo(model_5)
loo_5
```

Loo comparison
```{r}
loo_compare(loo_baseline,loo_2_test1,loo_2_test2,loo_2,loo_3,loo_4,loo_5_non_hier,loo_5)
```

```{r}
p1 <- pp_check(model_baseline) +
  ggtitle("Baseline model")
p2 <- pp_check(model_2) +
  ggtitle("2 effect model ")
p3 <- pp_check(model_3) +
  ggtitle("3 effect model ")
p4 <- pp_check(model_4) +
  ggtitle("4 effect model ")
p5 <- pp_check(model_5_non_hier) +
  ggtitle("5 effect non-hierarchical model")
p6 <- pp_check(model_5) +
  ggtitle("5 effect hierarchical model ")
```
```{r, fig.width=12, fig.height=8}
grid.arrange(p1, p2, p3, p4, p5, p6, nrow=3)
```




Posterior prediction with test data
```{r}
pp_baseline = posterior_predict(model_baseline,newdata=test_data)
pp_2 = posterior_predict(model_2,newdata=test_data)
pp_3 = posterior_predict(model_3,newdata=test_data)
pp_4 = posterior_predict(model_4,newdata=test_data)
pp_5_non_hier = posterior_predict(model_5_non_hier,newdata=test_data)
pp_5 = posterior_predict(model_5,newdata=test_data)

# descaling the data
cmax = max(train_data$charges)
cmin = min(train_data$charges)

pp_baseline = descaler(pp_baseline, cmax, cmin)
pp_2 = descaler(pp_2, cmax, cmin)
pp_3 = descaler(pp_3, cmax, cmin)
pp_4 = descaler(pp_4, cmax, cmin)
pp_5_non_hier = descaler(pp_5_non_hier, cmax, cmin)
pp_5 = descaler(pp_5, cmax, cmin)
```

Calculate prediction errors
```{r}
calculate_rmse <- function(true,predicted){
  rmse = sqrt(mean((true - predicted)^2)) 
  return(rmse)
}

calculate_r2 <- function(true, predicted){
  rss = sum((predicted - true)^2)
  tss = sum((true - mean(true))^2)
  return(1 - rss/tss)
}

rmse_baseline = calculate_rmse(test_data$charges, pp_baseline)
rmse_2 = calculate_rmse(test_data$charges, pp_2)
rmse_3 = calculate_rmse(test_data$charges, pp_3)
rmse_4 = calculate_rmse(test_data$charges, pp_4)
rmse_5_non_hier = calculate_rmse(test_data$charges, pp_5_non_hier)
rmse_5 = calculate_rmse(test_data$charges, pp_5)

#r2_baseline = calculate_r2(test_data$charges, pp_basic)
#r2_5 = calculate_r2(test_data$charges, pp_complex)

sprintf("Baseline model RMSE: %s", rmse_baseline)
sprintf("2 effect model RMSE: %s", rmse_2)
sprintf("3 effect model RMSE: %s", rmse_3)
sprintf("4 effect model RMSE: %s", rmse_4)
sprintf("5 effect non-hierarchical model RMSE: %s", rmse_5_non_hier)
sprintf("5 effect hierarchical model RMSE: %s", rmse_5)

#sprintf("Baseline model R2: %s", r2_baseline)
#sprintf("5 effect model R2: %s", r2_5)
```



